// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZhCA_hyYN0rI4NS-0SSM4qKTq5aPBF1s',
    appId: '1:350914998039:web:41bce1820c90f0bf4b9152',
    messagingSenderId: '350914998039',
    projectId: 'reposteria-arlex',
    authDomain: 'reposteria-arlex.firebaseapp.com',
    storageBucket: 'reposteria-arlex.firebasestorage.app',
    measurementId: 'G-REQ9EGFBYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZhCA_hyYN0rI4NS-0SSM4qKTq5aPBF1s',
    appId: '1:350914998039:android:41bce1820c90f0bf4b9152',
    messagingSenderId: '350914998039',
    projectId: 'reposteria-arlex',
    storageBucket: 'reposteria-arlex.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZhCA_hyYN0rI4NS-0SSM4qKTq5aPBF1s',
    appId: '1:350914998039:ios:41bce1820c90f0bf4b9152',
    messagingSenderId: '350914998039',
    projectId: 'reposteria-arlex',
    storageBucket: 'reposteria-arlex.firebasestorage.app',
    iosBundleId: 'com.example.reposteriaArlex',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZhCA_hyYN0rI4NS-0SSM4qKTq5aPBF1s',
    appId: '1:350914998039:ios:41bce1820c90f0bf4b9152',
    messagingSenderId: '350914998039',
    projectId: 'reposteria-arlex',
    storageBucket: 'reposteria-arlex.firebasestorage.app',
    iosBundleId: 'com.example.reposteriaArlex',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZhCA_hyYN0rI4NS-0SSM4qKTq5aPBF1s',
    appId: '1:350914998039:web:41bce1820c90f0bf4b9152',
    messagingSenderId: '350914998039',
    projectId: 'reposteria-arlex',
    authDomain: 'reposteria-arlex.firebaseapp.com',
    storageBucket: 'reposteria-arlex.firebasestorage.app',
    measurementId: 'G-REQ9EGFBYK',
  );
}